### ISSUE TITLE
Deploy job error - ClassNotFoundException: local

### ISSUE THREAD

**Issue by chaimaTPT** [vertica/PSTL#2]
Hi, 
When we deploy a simple job (like the example in the Getting Started wiki) we get this exception:

```
Exception in thread "main" java.lang.ClassNotFoundException: local
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:67)
        at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(DynamicAccess.scala:66)
        at scala.util.Try$.apply(Try.scala:161)
        at akka.actor.ReflectiveDynamicAccess.getClassFor(DynamicAccess.scala:66)
        at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
        at akka.actor.ActorSystemImpl.liftedTree1$1(ActorSystem.scala:585)
        at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:578)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
        at com.microfocus.pstl.Driver$.main(Driver.scala:31)
        at com.microfocus.pstl.Driver.main(Driver.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:750)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Any idea how to solve this?

I saw that you mentionned the Class Not Found Issue in the operations guide but not sure how to solve this (https://github.com/vertica/PSTL/wiki/Operations-Guide)

Thanks

**Comment by Bernard-Royet** [comment]
After investigations from Pravesh , it seems the problem was due to the Spark version used , 1.6 instead of 2.2
We changed SPARK_HOME to the right version , and the deploy script went further

**Comment by vnnv01** [comment]
Prerequisite of PSTL is Spark version should be 2.2. As you mentioned we have to set SPARK_HOME to right version for PSTL to work. Closing this issue but feel free of course to ask any more questions!
