### ISSUE TITLE
Job failed during deploy with Spark2.3 version

### ISSUE THREAD

**Issue by arumugaguru** [vertica/PSTL#4]
Hello,

We compiled the new PSTL with Spark 2.3 version and rpm got successfully build, but when tried to run a PSTL stream to stream join example, got the following error:

java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.FunctionRegistry.registerFunction(Lorg/apache/spark/sql/catalyst/FunctionIdentifier;Lscala/Function1;)V
        at com.microfocus.pstl.spark.SparkExtension$$anonfun$withSession$1$$anonfun$apply$1.apply(SparkExtension.scala:56)
        at com.microfocus.pstl.spark.SparkExtension$$anonfun$withSession$1$$anonfun$apply$1.apply(SparkExtension.scala:55)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at com.microfocus.pstl.spark.SparkExtension$$anonfun$withSession$1.apply(SparkExtension.scala:55)
        at com.microfocus.pstl.spark.SparkExtension$$anonfun$withSession$1.apply(SparkExtension.scala:52)
        at scala.collection.immutable.Stream.foreach(Stream.scala:594)
        at com.microfocus.pstl.spark.SparkExtension.withSession(SparkExtension.scala:52)
        at com.microfocus.pstl.Driver$.main(Driver.scala:38)
        at com.microfocus.pstl.Driver.main(Driver.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/04/23 04:00:20 INFO spark.SparkContext: Invoking stop() from shutdown hook
19/04/23 04:00:20 INFO server.AbstractConnector: Stopped Spark@3adbe50f{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
19/04/23 04:00:20 INFO ui.SparkUI: Stopped Spark web UI at http://15.120.132.182:4040
19/04/23 04:00:20 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/04/23 04:00:20 INFO memory.MemoryStore: MemoryStore cleared
19/04/23 04:00:20 INFO storage.BlockManager: BlockManager stopped
19/04/23 04:00:21 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
19/04/23 04:00:21 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/04/23 04:00:21 INFO spark.SparkContext: Successfully stopped SparkContext
19/04/23 04:00:21 INFO util.ShutdownHookManager: Shutdown hook called
19/04/23 04:00:21 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-e6c8e20b-ff90-44d9-87c4-8d9045262701

**Comment by vnnv01** [comment]
Set environment variable SPARK_HOME to spark 2.3 path and try reruning the job

**Comment by arumugaguru** [comment]
Thanks, it worked after changing the SPARK_HOME path pointing to 2.3 instead of our default 2.2 path.
